# Generated by Django 2.0.2 on 2019-01-03 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChinaCities',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('citycode', models.CharField(blank=True, max_length=100, null=True)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('shortname', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=100, null=True)),
                ('mergername', models.CharField(blank=True, max_length=100, null=True)),
                ('beento', models.IntegerField()),
            ],
            options={
                'db_table': 'china_cities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChinaProvinces',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('pinyin', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'china_provinces',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DistrictType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'district_type',
                'managed': False,
            },
        ),
    ]
