# Generated by Django 2.0.2 on 2019-01-03 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitcoin',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Bitcoin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bitcoincash',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'BitcoinCash',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ethereum',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Ethereum',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ethereumclassic',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'EthereumClassic',
                'managed': False,
            },
        ),
    ]
